// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr188ycN-sXiN8_6_FeLbSzQg5VqcudiY',
    appId: '1:315069282761:web:22f189f1e4ac9cb4921018',
    messagingSenderId: '315069282761',
    projectId: 'musicstore-app',
    authDomain: 'musicstore-app.firebaseapp.com',
    storageBucket: 'musicstore-app.appspot.com',
    measurementId: 'G-6MPETPEMJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtZjxRtaz7H3MBFzYukm-IA8nyhyowv_0',
    appId: '1:315069282761:android:5accd78be8e6610d921018',
    messagingSenderId: '315069282761',
    projectId: 'musicstore-app',
    storageBucket: 'musicstore-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCSO-goYKs2wwgwsh0jkpEeSyvHtnuPbI',
    appId: '1:315069282761:ios:c1d95779ec5bd11f921018',
    messagingSenderId: '315069282761',
    projectId: 'musicstore-app',
    storageBucket: 'musicstore-app.appspot.com',
    iosClientId: '315069282761-r98ducfsvs570ute6f1bltk4oc7qoaor.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicstoreApp',
  );
}
